In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("amazon_dataset2.csv", encoding='latin1')
df.head(10)

C:\Users\laksh\AppData\Local\Temp\ipykernel_26020\3944421990.py:1: DtypeWarning: Columns (0: B2B, 1: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("amazon_dataset2.csv", encoding='latin1')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0.0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1.0,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2.0,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3.0,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4.0,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
5,5.0,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,6.0,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
7,7.0,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
8,8.0,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
9,9.0,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,INR,363.00,Chennai,TAMIL NADU,600041.0,IN,NaN,False,NaN,NaN

# Changing Data-Types

In [3]:
df = df.drop(columns=['index']).reset_index(drop=True)
df.insert(0, 'index', range(1, len(df) + 1))

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128977 entries, 0 to 128976
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128977 non-null  int64
 1   Order ID            128977 non-null  str
 2   Date                128977 non-null  str
 3   Status              128977 non-null  str
 4   Fulfilment          128977 non-null  str
 5   Sales Channel       128977 non-null  str
 6   ship-service-level  128977 non-null  str
 7   Style               128977 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  float64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128940 non-null  str
 18  ship-postal-code    128940 non-null  float64
 19  ship-country        128940 non-null  str
 20  promotion-ids       79820 non-null   str
 21  B2B                 128973 non-null  object
 22  fulfilled-by        39275 non-null   str
 23  Unnamed: 22         79923 non-null   object
dtypes: float64(3), int64(1), object(2), str(18)
memory usage: 23.6+ MB

In [5]:
df.head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,1,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,2,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,3,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,4,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,5,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
5,6,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,7,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
7,8,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
8,9,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
9,10,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,INR,363.00,Chennai,TAMIL NADU,600041.0,IN,NaN,False,NaN,NaN

In [6]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='str')

In [ ]:
df['Date'] = pd.to_datetime(
    df['Date'],
    errors='coerce',
    format='mixed'
)

In [9]:
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

In [11]:
df.head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,1,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,2,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,3,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,4,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,5,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
5,6,404-1490984-4578765,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,7,408-5748499-6859555,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
7,8,406-7807733-3785945,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
8,9,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
9,10,402-4393761-0311520,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,INR,363.00,Chennai,TAMIL NADU,600041.0,IN,NaN,False,NaN,NaN

# Changing columns names

In [12]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_')

In [13]:
df.columns

Index(['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel',
       'ship_service_level', 'style', 'sku', 'category', 'size', 'asin',
       'courier_status', 'qty', 'currency', 'amount', 'ship_city',
       'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids',
       'b2b', 'fulfilled_by', 'unnamed:_22'],
      dtype='str')

# Deleting Column

In [14]:
df.drop(columns=['unnamed:_22'], inplace=True)

In [15]:
df.columns

Index(['index', 'order_id', 'date', 'status', 'fulfilment', 'sales_channel',
       'ship_service_level', 'style', 'sku', 'category', 'size', 'asin',
       'courier_status', 'qty', 'currency', 'amount', 'ship_city',
       'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids',
       'b2b', 'fulfilled_by'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128977 entries, 0 to 128976
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128977 non-null  int64
 1   order_id            128977 non-null  str
 2   date                128975 non-null  str
 3   status              128977 non-null  str
 4   fulfilment          128977 non-null  str
 5   sales_channel       128977 non-null  str
 6   ship_service_level  128977 non-null  str
 7   style               128977 non-null  str
 8   sku                 128975 non-null  str
 9   category            128975 non-null  str
 10  size                128975 non-null  str
 11  asin                128975 non-null  str
 12  courier_status      122103 non-null  str
 13  qty                 128975 non-null  float64
 14  currency            121180 non-null  str
 15  amount              121180 non-null  float64
 16  ship_city           128942 non-null  str
 17  ship_state          128940 non-null  str
 18  ship_postal_code    128940 non-null  float64
 19  ship_country        128940 non-null  str
 20  promotion_ids       79820 non-null   str
 21  b2b                 128973 non-null  object
 22  fulfilled_by        39275 non-null   str
dtypes: float64(3), int64(1), object(1), str(18)
memory usage: 22.6+ MB

# Handling Null Values

In [17]:
df.isnull().sum()

index                     0
order_id                  0
date                      2
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       2
category                  2
size                      2
asin                      2
courier_status         6874
qty                       2
currency               7797
amount                 7797
ship_city                35
ship_state               37
ship_postal_code         37
ship_country             37
promotion_ids         49157
b2b                       4
fulfilled_by          89702
dtype: int64

# Handling Missing Values in qty & amount column

In [18]:
df['qty'].unique()

array([ 0.,  1.,  2., 15.,  3.,  9., 13.,  5.,  4.,  8., nan])

In [21]:
df[(df['qty'] == 0) & (df['amount'] != 0)]

,index,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,...,qty,currency,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by
0,1,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,0.0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
3,4,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,0.0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
8,9,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,0.0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
23,24,404-6019946-2909948,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET291,SET291-KR-PP-M,Set,...,0.0,INR,570.48,pune,MAHARASHTRA,411044.0,IN,NaN,False,Easy Ship
29,30,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,...,0.0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128905,128906,406-3923120-4345139,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,JNE3801,JNE3801-KR-M,kurta,...,0.0,NaN,NaN,ANANTAPUR,ANDHRA PRADESH,515001.0,IN,NaN,False,NaN
128909,128910,403-6757403-6097100,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,NW014,NW014-ST-SR-XXXL,Set,...,0.0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,NaN,False,NaN
128910,128911,403-6757403-6097100,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,NW007,NW007-ST-CP-XXXL,Set,...,0.0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,NaN,False,NaN
128960,128961,408-9513596-4393945,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,SET058,SET058-KR-NP-L,Set,...,0.0,NaN,NaN,Bengaluru,KARNATAKA,560037.0,IN,NaN,False,NaN
128969,128970,404-5182288-1653947,2022-05-31,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,...,0.0,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,NaN,False,NaN

In [22]:
# Fill NaN first if needed
df['amount'] = df['amount'].fillna(0)

# Then fix mismatch
df.loc[df['qty'] == 0, 'amount'] = 0

In [ ]:
# checking if there are still mismatches
df[(df['qty'] == 0) & (df['amount'] != 0)]

Empty DataFrame
Columns: [index, order_id, date, status, fulfilment, sales_channel, ship_service_level, style, sku, category, size, asin, courier_status, qty, currency, amount, ship_city, ship_state, ship_postal_code, ship_country, promotion_ids, b2b, fulfilled_by]
Index: []

[0 rows x 23 columns]

In [25]:
df.isnull().sum()

index                     0
order_id                  0
date                      2
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       2
category                  2
size                      2
asin                      2
courier_status         6874
qty                       2
currency               7797
amount                    0
ship_city                35
ship_state               37
ship_postal_code         37
ship_country             37
promotion_ids         49157
b2b                       4
fulfilled_by          89702
dtype: int64

# Handling Null values in Currency Column

In [26]:
df['currency'].unique()

<StringArray>
['INR', nan]
Length: 2, dtype: str

In [ ]:
# Fill missing currency values with 'INR'
df['currency'] = df['currency'].fillna('INR')

In [30]:
df.isnull().sum()

index                     0
order_id                  0
date                      2
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       2
category                  2
size                      2
asin                      2
courier_status         6874
qty                       2
currency                  0
amount                    0
ship_city                35
ship_state               37
ship_postal_code         37
ship_country             37
promotion_ids         49157
b2b                       4
fulfilled_by          89702
dtype: int64

# Handling Null values in Courier_status

In [32]:
df['courier_status'].unique()

<StringArray>
[nan, 'Shipped', 'Cancelled', 'Unshipped']
Length: 4, dtype: str

In [ ]:
# Fill missing courier_status values with 'Unknown'
df['courier_status'] = df['courier_status'].fillna('Unknown')

In [34]:
df['courier_status'].unique()

<StringArray>
['Unknown', 'Shipped', 'Cancelled', 'Unshipped']
Length: 4, dtype: str

In [35]:
df.isnull().sum()

index                     0
order_id                  0
date                      2
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       2
category                  2
size                      2
asin                      2
courier_status            0
qty                       2
currency                  0
amount                    0
ship_city                35
ship_state               37
ship_postal_code         37
ship_country             37
promotion_ids         49157
b2b                       4
fulfilled_by          89702
dtype: int64

# Deleting Null Rows from Columns

In [36]:
df = df.dropna(subset=[
    'date',
    'sku',
    'category',
    'size',
    'asin',
    'qty',
    'ship_city',
    'ship_state',
    'ship_postal_code',
    'ship_country',
    'b2b'
])
print("Rows after cleaning:", df.shape)

Rows after cleaning: (128940, 23)

In [37]:
df.isnull().sum()

index                     0
order_id                  0
date                      0
status                    0
fulfilment                0
sales_channel             0
ship_service_level        0
style                     0
sku                       0
category                  0
size                      0
asin                      0
courier_status            0
qty                       0
currency                  0
amount                    0
ship_city                 0
ship_state                0
ship_postal_code          0
ship_country              0
promotion_ids         49145
b2b                       0
fulfilled_by          89678
dtype: int64

# Handling null values in fulfilled_by column

In [39]:
df['fulfilled_by'].unique()

<StringArray>
['Easy Ship', nan]
Length: 2, dtype: str

In [40]:
df['fulfilled_by'] = df['fulfilled_by'].fillna('Non-Easy Ship')

In [41]:
df['fulfilled_by'].unique()

<StringArray>
['Easy Ship', 'Non-Easy Ship']
Length: 2, dtype: str

# Handling Null Values in promotion_ids

In [43]:
df['promotion_ids'] = df['promotion_ids'].fillna('No Promotion')

In [44]:
df.isnull().sum()

index                 0
order_id              0
date                  0
status                0
fulfilment            0
sales_channel         0
ship_service_level    0
style                 0
sku                   0
category              0
size                  0
asin                  0
courier_status        0
qty                   0
currency              0
amount                0
ship_city             0
ship_state            0
ship_postal_code      0
ship_country          0
promotion_ids         0
b2b                   0
fulfilled_by          0
dtype: int64